### ISSUE TITLE
Oh man they really screwed us

### ISSUE THREAD

**Issue by toadkicker** [JamieMason/custom-linkedin-cv#3]
I just started plugging away at this again and I found out LinkedIn changed their API structure now. The r_fullprofile permission is no longer available unless a developer goes through their new application process. I'm going to try to get access to it and make something more serious for this thing. I'm thinking I'll host the app so people can pull their own CV's using it.

**Comment by JamieMason** [comment]
That sounds great @toadkicker. 

I wish I had more time to work on this project as I'd find it really useful, but this project is a long way from that. Best of luck, keep me posted.
